### ISSUE TITLE
Clarify the text to make sure that people do not get the impression that CDNs are mandatory

### ISSUE THREAD

**Issue by ties** [timbru/draft-sidrops-publication-server-bcp#13]
I got feedback at IETF from someone that they interpreted the document as strongly recommending using a CDN. I do not think this is our shared opinion. I think our opinion is that this is a _strong option_ but that the service quality equivalent (or maybe has more grey failures) than a very solid distribution infrastructure.

**Comment by timbru** [comment]
Ok, we should think about phrasing...

Using a CDN is probably the easiest and most cost-effective way to tap into an existing distribution structure. But, setting up one's structure for organisations with the required resources is fine. We are trying to enumerate the cases operators must consider rather than dictate one way to do all this. At least, that's my goal with this.
